language: ruby
rvm:
  - 2.2.3
before_script:
  - psql -c 'create database statusify_test;' -U postgres
  - rm config/database.yml
  - cp config/database.ci.yml config/database.yml
bundler_args: --without production
cache: bundler
